---
- include_vars: ../../common_vars.yml

- name: Set variables
  set_fact:
    control_plane_dir: '{{playbook_dir}}/resources/control-plane'
    go_bin: '/usr/local/go/bin'
    go_path: "{{ lookup('env', 'HOME') }}/go"

- name: Install Git
  become: yes
  apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Get toml parser library for Golang
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  shell: "go get github.com/BurntSushi/toml"

- name: Get psql drive for Golang
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  shell: "go get gopkg.in/pg.v5"

- name: Build Control Plane API
  become: yes
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  shell: "go build -o {{control_plane_dir}}/snowplow-mini-control-plane-api {{control_plane_dir}}/*.go"

- name: Copy Control API to executables dir
  become: yes
  shell: cp {{control_plane_dir}}/snowplow-mini-control-plane-api {{executables_dir}}

- name: Get Caddyserver build
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  shell: |
    export GO111MODULE=on
    go get github.com/mholt/caddy/caddy

- name: Copy Caddy executable to executables dir
  become: yes
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  synchronize:
    src: "/$GOPATH/bin/caddy"
    dest: "{{executables_dir}}"
