---
- name: Update apt cache
  apt: update-cache=yes cache_valid_time=86400
  sudo: yes

- name: install basic packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - curl
    - unzip

- name: Add Google DNS nameserver
  lineinfile:
    dest="/etc/resolvconf/resolv.conf.d/base"
    line="nameserver 8.8.8.8"
  sudo: yes

- name: Update nameserver list
  command: "resolvconf -u"
  sudo: yes
